258-A2-Tom-Milne/Models/UserHomeViewModel.cs
using System.Collections.Generic;
using _258_A2_Tom_Milne.Models; 

public class UserHomeViewModel
{
    public List<Project> Projects { get; set; }
    public List<ProjectTask> ProjectTasks { get; set; }
}

258-A2-Tom-Milne/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Data;
using _258_A2_Tom_Milne.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace _258_A2_Tom_Milne.Controllers
{
    public class ProjectController : Controller
    {
        private readonly A2DbContext _context;
        private readonly UserManager<IdentityUser> _userManager;


        public ProjectController(UserManager<IdentityUser> userManager, A2DbContext context)
        {
            _context = context;
            _userManager = userManager;
        }

        //Modified index action which passes list of projects to be displayed based on the logged in user
        //Authorize annotation as only authenticated user can acc
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            // Get the UserId of the logged-in user
            var userId = user.Id;

            // Filter the projects by UserId
            var userProjects = await _context.Project
                .Where(p => p.UserId == userId)
                .ToListAsync();

            return View(userProjects);
        }

        // GET: Project/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Project == null)
            {
                return NotFound();
            }

            var project = await _context.Project
                .FirstOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Project/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Project/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //modified to associate projects with a user.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,DateStart,DateEnd,UserId")] Project project)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                project.UserId = user.Id;

                
                _context.Add(project);
                await _context.SaveChangesAsync();
                int projectId = project.Id;

                return RedirectToAction("ProjectDetails", "UserHome", new { projectId });//upon creation redirect to project details action

            }
            //debug code
            else
            {
                foreach (var modelState in ViewData.ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        Console.WriteLine(error.ErrorMessage);
                    }
                }
                return View(project);
            }
        }

        // GET: Project/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Project == null)
            {
                return NotFound();
            }

            var project = await _context.Project.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            return View(project);
        }

        // POST: Project/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Date,UserId")] Project project)
        {
            if (id != project.Id)
            {
                return NotFound();
            }
            var projectId = id;
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("ProjectDetails", "UserHome", new { projectId });
            }
            return View(project);
        }

        // GET: Project/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Project == null)
            {
                return NotFound();
            }

            var project = await _context.Project
                .FirstOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Project/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Project == null)
            {
                return Problem("Entity set 'A2DbContext.Project'  is null.");
            }
            var project = await _context.Project.FindAsync(id);
            if (project != null)
            {
                _context.Project.Remove(project);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectExists(int id)
        {
          return (_context.Project?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

258-A2-Tom-Milne/Controllers/ProjectTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Data;
using _258_A2_Tom_Milne.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.CodeAnalysis;
using Microsoft.Build.Evaluation;

namespace _258_A2_Tom_Milne.Controllers
{
    public class ProjectTaskController : Controller
    {
        private readonly A2DbContext _context;
        private readonly UserManager<IdentityUser> _userManager;


        public ProjectTaskController(UserManager<IdentityUser> userManager, A2DbContext context)
        {
            _context = context;
            _userManager = userManager;


        }

        // GET: ProjectTask
        public async Task<IActionResult> Index()
        {
            var a2DbContext = _context.ProjectTask.Include(p => p.Project);
            return View(await a2DbContext.ToListAsync());
        }

        // GET: ProjectTask/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ProjectTask == null)
            {
                return NotFound();
            }

            var projectTask = await _context.ProjectTask
                .Include(p => p.Project)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (projectTask == null)
            {
                return NotFound();
            }

            return View(projectTask);
        }

        // GET: ProjectTask/Create
        public IActionResult Create()
        {
            
            return View();
        }

        // POST: ProjectTask/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //Modified to display project tasksbased on a passed projectId
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Date,ProjectId")] ProjectTask projectTask, int projectId)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);


                if (user != null)
                {

                    
                    projectTask.UserId = user.Id;
                    projectTask.ProjectId = projectId;


                    // Set the ProjectId of the ProjectTask to match the retrieved Project's Id


                    _context.Add(projectTask);

                    // Save changes
                    await _context.SaveChangesAsync();

                    return RedirectToAction("ProjectDetails", "UserHome", new { projectId });//redirects to the same Projectdetails page it is called from
                    
                }
            }
            //debug code
            else
            {
                foreach (var modelState in ViewData.ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        Console.WriteLine(error.ErrorMessage);
                    }
                }
            }

            return View(projectTask);
        }

        // GET: ProjectTask/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ProjectTask == null)
            {
                return NotFound();
            }

            var projectTask = await _context.ProjectTask.FindAsync(id);
            if (projectTask == null)
            {
                return NotFound();
            }
            ViewData["ProjectId"] = new SelectList(_context.Project, "Id", "Id", projectTask.ProjectId);
            return View(projectTask);
        }

        // POST: ProjectTask/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Date,ProjectId")] ProjectTask projectTask)
        {
            if (id != projectTask.Id)
            {
                return NotFound();
            }
            var projectId = projectTask.ProjectId;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(projectTask);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectTaskExists(projectTask.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("ProjectDetails", "UserHome", new { projectId });
            }
            ViewData["ProjectId"] = new SelectList(_context.Project, "Id", "Id", projectTask.ProjectId);
            return View(projectTask);
        }

        // GET: ProjectTask/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ProjectTask == null)
            {
                return NotFound();
            }

            var projectTask = await _context.ProjectTask
                .Include(p => p.Project)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (projectTask == null)
            {
                return NotFound();
            }

            return View(projectTask);
        }

        // POST: ProjectTask/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ProjectTask == null)
            {
                return Problem("Entity set 'A2DbContext.ProjectTask'  is null.");
            }
            var projectTask = await _context.ProjectTask.FindAsync(id);
            if (projectTask != null)
            {
                _context.ProjectTask.Remove(projectTask);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectTaskExists(int id)
        {
          return (_context.ProjectTask?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

258-A2-Tom-Milne/Controllers/UserHomeController.cs
using _258_A2_Tom_Milne.Areas.Identity.Data;
using _258_A2_Tom_Milne.Models;
using Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

//Custom controller for handling actions related to the user home page. I used UserManager class from Identity to
//handle tracking logged in user. I then used this to populate a view model with projects associated with that user
//All actions only available to authenticated user
[Authorize]
public class UserHomeController : Controller
{
    private readonly UserManager<IdentityUser> _userManager;
    private readonly A2DbContext _a2DbContext;

    public UserHomeController(UserManager<IdentityUser> userManager,  A2DbContext a2DbContext)
    {
        _userManager = userManager;
        _a2DbContext = a2DbContext;
    }

    //use UserManager to get lists of Projects and projecttasks with a userId matching the user
    public async Task<IActionResult> Index()
    {
        // Get the current user
        var user = await _userManager.GetUserAsync(User);

        // Fetch user-specific data related to projects and ProjectTasks based on the id of logged in user, use linq to order by date 
        var userProjects = _a2DbContext.Project.Where(p => p.UserId == user.Id).OrderBy(p => p.DateEnd).ToList();

        var userProjectTasks = userProjects
        .SelectMany(project => _a2DbContext.ProjectTask.Where(pt => pt.ProjectId == project.Id))
        .OrderBy(pt => pt.Date)
        .ToList();

        // Create a ViewModel to pass data to the view
        var viewModel = new UserHomeViewModel
        {
            Projects = userProjects,
            ProjectTasks = userProjectTasks
        };

        return View(viewModel);
    }

    //works in a similar way but takes a projectId variable to store a list of Project tasks with matching projectId
    public IActionResult ProjectDetails(int projectId)
    {
        var project = _a2DbContext.Project.Include(p => p.ProjectTasks).SingleOrDefault(p => p.Id == projectId);
        if (project == null)
        {
            return NotFound();
        }
        //create model using data from the project with the passed Id
        var viewModel = new ProjectViewModel
        {
            ProjectId = project.Id,
            Project = project,
            ProjectTasks = project.ProjectTasks.ToList()
        };

        return View(viewModel);
    }

    //Create a new SearchView model based on the searchTerm and SelectedFilter
    [Authorize]
    public async Task<IActionResult> Search(string searchTerm, string selectedFilter)
    {
        // Get the current user
        var user = await _userManager.GetUserAsync(User);

        // Filter matching projects and tasks by UserId
        var matchingProjects = _a2DbContext.Project
            .Where(p => p.UserId == user.Id && p.Title.Contains(searchTerm))
            .ToList();

        var matchingTasks = _a2DbContext.ProjectTask
            .Where(pt => pt.Project.UserId == user.Id && pt.Title.Contains(searchTerm))
            .ToList();

        // Create a view model to display the search results
        var viewModel = new SearchViewModel
        {
            SearchTerm = searchTerm,
            filterTerm = selectedFilter,
            Projects = matchingProjects,
            Tasks = matchingTasks
        };

        return View("SearchResult", viewModel);
    }

}

258-A2-Tom-Milne/Views/UserHome/Index.cshtml
@model UserHomeViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "_LayoutUser";
}
<head>
    <link rel="stylesheet" href="~/css/UserHomeStyle.css" asp-append-version="true" />
</head>
<div class="userhome-container">
    <div class="left-sidebar">
        <h4 id="project-header">Projects</h4>
        <!--Table to display the users projects-->
        <table class="table">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Finish Date</th>
                </tr>
            </thead>
            
            <tbody>
                @foreach (var project in Model.Projects)
                {
                    <tr>
                        <!--display the project title as a link which calls ProjectDetails action and passes the project id
                            this directs to the ProjectDetails view for that project-->
                        <td><a asp-action="ProjectDetails" asp-controller="UserHome" asp-route-projectId="@project.Id">@project.Title</a></td>

                        <td>@project.DateEnd</td>
                        <td><a asp-action="Delete" asp-controller="Project" asp-route-id="@project.Id">Delete</a></td>
                    </tr>
                }
            </tbody>
        </table>
        <!--I used the .NET generated Create view for creating Projects-->
        <a asp-action="Create" asp-controller="Project" class="btn">Create New Project</a>
    </div>

    <!--This section displays a calendar with projects or project tasks based on the option value of the select-->
    <div class="middle-section">
        <select class="form-control" id="filter" style="margin-bottom:5px">
            <option value="Projects">Projects</option>
            <option value="Project Tasks">Project Tasks</option>
        </select>
        <div id="calendar"></div>
    </div>


</div>
<!-- This script uses the fullCalendar package:https://cdn.jsdelivr.net/npm/fullcalendar@6.1.9/index.global.min.js to load and display
    a calendar and populate it with data from my Project and ProjectTask models-->
<script>

    //function to load the calendar
    function loadCalendar(selectedFilter) {

        var calendarEl = document.getElementById('calendar'); //get the div where the calendar will display
        var calendar = new FullCalendar.Calendar(calendarEl, { //initialize using the Calendar method from FullCalendar, passing the div
            initialView: 'dayGridMonth', //set view to display single month
            eventClick: function (info) { //set event for clicking some object within the calender
                window.location = info.event.url;
            }
        });

        calendar.removeAllEvents(); // Clear existing events so that we can re load calender when select is toggled

        var events = []; //initialise array of calendar events

        //loops through a model based on the condition of the select value. Uses razor syntax to generate event objects and add them to array
        if (selectedFilter == 'Projects') {
            @foreach (var project in Model.Projects)
            {
                @:events.push({
                @:    title: '@project.Title',
                @:    start: '@project.DateStart.ToString("yyyy-MM-dd")',
                @:    end: '@project.DateEnd.ToString("yyyy-MM-dd")',
                @:    url: '@Url.Action("ProjectDetails", "UserHome", new { projectId = @project.Id })'
                @:});
            }
        }
        if (selectedFilter == 'Project Tasks') {
            @foreach (var projectTask in Model.ProjectTasks)
            {
                @:events.push({
                @:    title: '@projectTask.Title',
                @:    start: '@projectTask.Date.ToString("yyyy-MM-dd")',
                @:    url: '@Url.Action("ProjectDetails", "UserHome", new { projectId = projectTask.ProjectId })'
                @:});
            }
        }

        calendar.addEventSource(events); // Add new events to the calendar

        calendar.render();
    }

    //calls the loadcalender function and sets event listener for the select so that calendar can be re loaded on change
    function initializePage() {
        const filter = document.getElementById('filter');
        filter.addEventListener('change', function () {
            const selectedFilter = filter.value;
            loadCalendar(selectedFilter);
        });

        loadCalendar(filter.value); // Load calendar when the page loads
    }

    document.addEventListener('DOMContentLoaded', initializePage);
</script>
<script>initializeCalendar();</script>

258-A2-Tom-Milne/Views/UserHome/ProjectDetails.cshtml
@model _258_A2_Tom_Milne.Models.ProjectViewModel

@{
    ViewData["Title"] = "Project Details";
    Layout = "_LayoutUser";
    var projectId = Model.ProjectId;

}

<head>
    <link rel="stylesheet" href="~/css/UserHomeStyle.css" />
</head>
<!--This section displays data from the project model. Input tags are used with the readoly attribute so that the fields can be
    toggled between being editable and non editable-->
<div class="userhome-container">
    <div class="left-sidebar">
        <label for="projectTitle_@Model.Project.Id">Project Title</label>
        <input class="form-control editable-field" id="projectTitle_@Model.Project.Id" readonly="readonly" value="@Model.Project.Title" />

        <label for="projectDescription_@Model.Project.Id">Project Description</label>
        <input class="form-control editable-field" id="projectDescription_@Model.Project.Id" readonly="readonly" value="@Model.Project.Description" />

        <label for="projectDate_@Model.Project.Id">Finish Date:</label>
        <input type="date" class="form-control editable-field" id="projectDate_@Model.Project.Id" readonly="readonly" value="@Model.Project.DateEnd.ToString("yyyy-MM-dd")" />
        <a asp-action="Edit" asp-controller="Project" asp-route-id="@Model.Project.Id">Edit</a><button id="toggleForm" class="btn btn-primary">Add Project Task</button>

        <!--Use razor syntax to return and display a partial view responsible for creating new tasks and adding them within the projects.
    This approach allows the form to be displayed within the page-->
        @Html.Partial("_CreateTaskForm", new _258_A2_Tom_Milne.Models.ProjectTask { ProjectId = projectId })

    </div>

    <!--This section displays the tasks associated with the project. I used css to make the list of tasks scroll independantly
        I used boostrap card class to display each task-->
    <div class="middle-section">
        <h5>Project Tasks</h5>
        <div class="scrollable-container">
            @foreach (var task in Model.ProjectTasks)
            {
                <div class="card" style="margin-bottom: 10px">
                    <div class="card-body">
                        <div class="row" style="border-bottom: 1px solid #ccc;">
                            <div class="col-md-6">
                                <label for="taskTitle_@task.Id">Title:</label>
                                <input class="form-control editable-field" id="taskTitle_@task.Id" readonly="readonly" value="@task.Title" />
                            </div>
                            <div class="col-md-6">
                                <label for="taskDate_@task.Id">Finish Date:</label>
                                <input type="date" class="form-control editable-field" id="taskDate_@task.Id" readonly="readonly" value="@task.Date.ToString("yyyy-MM-dd")" />
                            </div>
                        </div>
                        <div class="col-md-12">
                            <h6>Description:</h6>
                            <textarea class="form-control editable-field" id="taskDescription_@task.Id" readonly="readonly">@task.Description</textarea>
                        </div>
                        <a asp-action="Edit" asp-controller="ProjectTask" asp-route-id="@task.Id">Edit</a>

                    </div>
                </div>
            }
        </div>

    </div>
</div>

<!--This script toggles the display of the partial view for adding tasks between no display and block display-->
<script>document.getElementById("toggleForm").addEventListener("click", function () {
        const form = document.getElementById("projectTaskForm");
        if (form.style.display === "none" || form.style.display === "") {
            form.style.display = "block";
        } else {
            form.style.display = "none";
        }
    });

    document.getElementById("cancelButton").addEventListener("click", function () {
        const form = document.getElementById("projectTaskForm");
        form.style.display = "none";
    });</script>

258-A2-Tom-Milne/Views/UserHome/SearchResult.cshtml
@model SearchViewModel
@{
    ViewData["Title"] = "Search Results";
    Layout = "_LayoutUser";

}
<head>
    <link rel="stylesheet" href="~/css/UserHomeStyle.css" />
</head>
<h1>Search Results for "@Model.SearchTerm"</h1>


<!--I used a simple viewmodel for displaying search results. Conditionaly displays results based on a filter term
    which comes from a select element in the layout-->
@if (Model.filterTerm == "Projects" || Model.filterTerm == "All")
{
    <h2>Projects</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Finish Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var project in Model.Projects)
            {
                <tr>
                    <td><a asp-action="ProjectDetails" asp-controller="UserHome" asp-route-projectId="@project.Id">@project.Title</a></td>
                    <td>@project.Description</td>
                    <td>@project.DateEnd</td>
                    <td>@project.Id</td>
                </tr>
            }
        </tbody>
    </table>
}

@if (Model.filterTerm == "Project Tasks" || Model.filterTerm == "All")
{
    <h2>Tasks</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Finish Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var task in Model.Tasks)
            {
                <tr>
                    <td>@task.Title</td>
                    <td>@task.Description</td>
                    <td>@task.Date</td>
                    <td>@task.Id</td>

                </tr>
            }
        </tbody>
    </table>
}